### ISSUE TITLE
Assembly signing not supported

### ISSUE THREAD

**Issue by georgesak84** [redhat-developer/s2i-dotnetcore#203]
i am getting an error when trying to build on openshift with a netcore project.

error CS7027: Error signing output with public key from file 'filename.snk' -- Assembly signing not supported.

any way to add signed assemblies?

**Comment by tmds** [comment]
Are you using 2.0? It may work on 2.1. If it doesn't, you can disable the signing, see https://github.com/dotnet/cli/issues/6911.

**Comment by georgesak84** [comment]
Yes i am using 2.0 but now i downloaded the 2.1 and we were able to keep the signing. thanks alot

**Comment by tmds** [comment]
No problem, glad it is working now!
