### ISSUE TITLE
Double restore issue with OS origin v1.5.0-alpha2

### ISSUE THREAD

**Issue by nmilosev** [redhat-developer/s2i-dotnetcore#43]
Hello, 

When running the `dotnetcore1.1` image on the latest origin docker image:

```
OpenShift Master:
v1.5.0-alpha.2+708ea98-310
Kubernetes Master:
v1.5.2+43a9be4
```

and trying to build the sample application packages seem to get restored twice: 

```
Cloning "https://github.com/redhat-developer/s2i-dotnetcore-ex.git" ...
	Commit:	e3e6e5f848b97b148049fe1c6c2a4f7362091821 (Add .NET Core 1.1 support (#21))
	Author:	Severin Gehwolf <jerboaa@gmail.com>
	Date:	Tue Jan 31 10:27:14 2017 +0100
---> Copying application source ...
---> Installing dependencies ...
log  : Restoring packages for /opt/app-root/src/project.json...
log  : Restoring packages for /opt/app-root/src/app/project.json...
log  : Installing Microsoft.VisualStudio.Web.CodeGeneration.Utils 1.0.0-preview2-final.
...
```

This results in a lot of compiler errors for double declarations as so:

```
...
/opt/app-root/src/app/Controllers/ManageController.cs(68,42): error CS0111: Type 'ManageController' already defines a member called 'RemoveLogin' with the same parameter types
/opt/app-root/src/app/Controllers/ManageController.cs(86,30): error CS0111: Type 'ManageController' already defines a member called 'AddPhoneNumber' with the same parameter types
/opt/app-root/src/app/Controllers/ManageController.cs(95,42): error CS0111: Type 'ManageController' already defines a member called 'AddPhoneNumber' with the same parameter types
/opt/app-root/src/app/Controllers/ManageController.cs(112,42): error CS0111: Type 'ManageController' already defines a member called 'EnableTwoFactorAuthentication' with the same parameter types
/opt/app-root/src/app/Controllers/ManageController.cs(128,42): error CS0111: Type 'ManageController' already defines a member called 'DisableTwoFactorAuthentication' with the same parameter types
/opt/app-root/src/app/Controllers/ManageController.cs(143,42): error CS0111: Type 'ManageController' already defines a member called 'VerifyPhoneNumber' with the same parameter types
...
```

**When running on the latest stable version of Origin (v1.4.1) everything is fine, so this is a regression.**

I've also tried another application which works on v1.4.1, thinking it's a `project.json` issue, but got the same results.

Host is virtualized Fedora 25 Server in both test cases, running openshift on a single node (`oc cluster up`). The issue may be that my `oc` client tools are v1.3.1 but I am unsure how this affects the restoration process.

Nemanja

**Comment by jerboaa** [comment]
How can we reproduce this? What steps are you running precisely? Are you using a self built image?

**Comment by jerboaa** [comment]
What's odd is this:

> ---> Installing dependencies ...
> log  : Restoring packages for /opt/app-root/src/project.json...
> log  : Restoring packages for /opt/app-root/src/app/project.json...

So the streamed app sources seem to have two `project.json` files? When this is https://github.com/redhat-developer/s2i-dotnetcore-ex/tree/dotnetcore-1.1 there is only one under folder `app`. As to double restore, I don't see evidence of this.

**Comment by nmilosev** [comment]
The image is not self built.

I'm following this: https://github.com/redhat-developer/s2i-dotnetcore-ex/tree/dotnetcore-1.1

Steps to reproduce:

1. Run `origin:latest` with `oc cluster up --version='v1.4.1'`
2. Get the `dotnetcore1.1` template (imported YAML through Web console) and make a new example ASP.NET Core application with it

Same steps work when using `origin:v1.4.1` but compilation fails with the latest image.

**Comment by nmilosev** [comment]
I think that would be the same. I got the raw template json from github and uploaded it to the web console.

On Fedora 25, with origin 1.4.1 image works perfectly with several applications. 

Maybe error in the new version of origin?

**Comment by jerboaa** [comment]
If this cannot be reproduced with 1.4.1 origin (latest stable), it's worth talking to origin developers.

**Comment by nmilosev** [comment]
I can't reproduce it with v1.4.1 origin, just wanted to give a heads up if something is changed for the next release.

I have several applications running on v1.4.1 all day, and so far no issues.

**Comment by jerboaa** [comment]
It has been pointed out to me that this is https://github.com/openshift/origin/pull/12628 I.e. an issue with the sti-builder image. Nothing to do with the dotnet image. Please try again with an image that includes the fix.

**Comment by tmds** [comment]
@nmilosev there was a regression in the fix, which got fixed yesterday: https://github.com/openshift/origin/pull/12891. Thanks for reporting.

**Comment by nmilosev** [comment]
@tmds Thank you, will try it out.
